### ISSUE TITLE
Windows package

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/r-arrow-feedstock#3]
As a py37/r36/win64 user it would be great if there were a Windows conda package for `r-arrow`.

I understand Windows support is probably more difficult but I'd like to follow along if there are any issues detailing the problems?

**Comment by dbast** [comment]
Let's give it a try, see https://github.com/conda-forge/r-arrow-feedstock/pull/4

**Comment by dbast** [comment]
A win build could be possible now as there was some upstream work, see e.g. https://github.com/apache/arrow/commit/1d588ab35241792f2e702e90ba331e9dc659354a

**Comment by xhochy** [comment]
I did some work on this in #15 by using clang as a compiler. It doesn't work but I'm very close to it. The main challenging problem here is that `arrow-cpp` is built using MSVC whereas the R ecosystem is built using MinGW. 

### What was done

- Built using `clang/clangxx` as the compilers on Windows
- Custom `configure.win` (much more simplified)
- Patching `$BUILD_PREFIX/Lib/R/library/Rcpp/include/Rcpp/DataFrame.h` to compile with `clang++`
- Patching `$BUILD_PREFIX/Lib/R/etc/x64/Makeconf` to use `clang++` and `llvm-nm`

### Manual workarounds needed

Build the recipe until it fails, then

1. `conda install -y m2w64-tools-git m2w64-binutils && cd ..\_h_env\Lib\R\bin\x64 && gendef R.dll && dlltool -d R.def -l R.lib; cd -`
2.`R CMD INSTALL --build r`
3. `cd r/src`; Run the failed linker command from above without `tmp.def` in it; `cd -`
4. `R CMD INSTALL --build r`

### Open issues

This now proceeds until 
```
Error in inDL(x, as.logical(local), as.logical(now), ...) : unable to load shared object 'C:/Users/Administrator/miniconda3/conda-bld/r-arrow_1585632953035/work/r/src/arrow.dll': 
        LoadLibrary failure: %1 is not a valid Win32 application.
```

The issue here is that R produces `arrow.dll` in its local path that links to `arrow.dll` in `%LIBRARY_PREFIX%/bin/arrow.dll`. As both libraries are named the same, we need to rename one of them, preferably the R one: https://issues.apache.org/jira/browse/ARROW-8281

cc @nealrichardson

**Comment by dhirschfeld** [comment]
Thanks for looking into this @xhochy! I'm now following along in #15 too.

It sounds like conda might need a mutex of the Windows C++ compiler used?

**Comment by xhochy** [comment]
With the current progress in #15 this it not needed at least for Arrow anymore. I rather need an expert in the R build system to figure out how my awful hacks can be done with normal R options.
